apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: nat-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.0.2.100-10.0.2.150  # Plage réservée dans votre sous-réseau NAT
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: nat-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - nat-pool
