version: '3.8'

services:
  microservice:
    image: mbrabaa2023/gestion-trajets
    container_name: microservice.1
    expose:
    - "8080"  # Force l'exposition même si l'image ne le déclare pas
    ports:
      - "8081:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - monitoring_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/stub_status"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter
    container_name: nginx_exporter
    ports:
      - "9113:9113"
    command:
      - '-nginx.scrape-uri=http://microservice:8080/stub_status'
    networks:
      - monitoring_net
    depends_on:
      microservice:
        condition: service_healthy
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: monitoring_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring_net
    depends_on:
      nginx-exporter:
        condition: service_started
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: monitoring_grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-dashboards:/etc/grafana/provisioning/dashboards
    environment:
      GF_SECURITY_ADMIN_PASSWORD: rabaa123
      GF_USERS_DEFAULT_THEME: light
    networks:
      - monitoring_net
    depends_on:
      prometheus:
        condition: service_started
    restart: unless-stopped

volumes:
  grafana-storage:

networks:
  monitoring_net:
    driver: bridge
    attachable: true