version: '3'

services:
  nodejs-app:
    build: ../  # Pointe vers la racine pour utiliser le Dockerfile
    ports:
      - "8081:8080"
    environment:
      - PORT=8080

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - nodejs-app

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin