global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'gestion-trajet'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['votre-service:3000'] # À adapter
