apiVersion: v1
kind: ConfigMap
metadata:
  name: gestion-trajet-config
  namespace: microservice-1
data:
  NODE_ENV: "development"
  PORT: "5000"
  DATABASE_URL: postgres://tunisbus:tunisbus@postgres:5432/tunisbusdb
  VITE_API_URL: "http://localhost:5000/api"
