apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestion-trajet-app
  namespace: microservice-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gestion-trajet
  template:
    metadata:
      labels:
        app: gestion-trajet
    spec:
      containers:
        - name: gestion-trajet
          image: mbrabaa2023/microservice-1:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: gestion-trajet-secrets
                  key: DATABASE_URL
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: gestion-trajet-config
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: gestion-trajet-config
                  key: PORT
            - name: VITE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: gestion-trajet-config
                  key: VITE_API_URL
          resources:
            limits:
              memory: "512Mi"  # Limite de mémoire
              cpu: "500m"      # Limite de CPU
            requests:
              memory: "256Mi"  # Requête de mémoire (minimale requise)
              cpu: "250m"      # Requête de CPU (minimale requise)
          volumeMounts:
            - name: app-storage
              mountPath: /app/data  # Le répertoire pour les données
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: gestion-trajet-pvc  # Référence le PVC
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gestion-trajet-pv
  namespace: microservice-1
spec:
  capacity:
    storage: 1Gi  # Taille du PV
  accessModes:
    - ReadWriteOnce  # Mode d'accès
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/gestion-trajet  # Répertoire sur le nœud hôte
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gestion-trajet-pvc
  namespace: microservice-1
spec:
  accessModes:
    - ReadWriteOnce  # Mode d'accès
  resources:
    requests:
      storage: 1Gi  # Taille demandée pour le PVC
