apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestion-trajet  # Nom aligné avec le workflow
  namespace: microservice
  labels:
    app: gestion-trajet
    tier: backend
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: gestion-trajet
  template:
    metadata:
      labels:
        app: gestion-trajet
        version: v1.0.0
    spec:
      imagePullSecrets:
      - name: regcred  # Secret pour l'authentification Docker
      containers:
      - name: app
        image: mbrabaa2023/gestion_trajet:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        envFrom:
        - secretRef:
            name: gestion-trajet-secrets
        - configMapRef:
            name: gestion-trajet-config
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false