apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestion-trajet
  namespace: microservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gestion-trajet
  template:
    metadata:
      labels:
        app: gestion-trajet
    spec:
      imagePullSecrets:
      - name: local-image-pull
      containers:
      - name: app
        image: mbrabaa2023/gestion_trajet:latest
        imagePullPolicy: IfNotPresent  # Modifié
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: gestion-trajet-secrets
        - configMapRef:
            name: gestion-trajet-config