apiVersion: v1
kind: Service
metadata:
  name: db-host  # Doit correspondre à DB_HOST dans les secrets
  namespace: microservice-1
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432