apiVersion: v1
kind: Secret
metadata:
  name: gestion-trajet-secrets
  namespace: microservice
type: Opaque
data:
  DB_HOST: ZGItaG9zdA==
  DB_PORT: NTQzMg==
  DB_USER: ZGJfdXNlcg==
  DB_PASSWORD: MDAwMA==  # 0000
  JWT_SECRET: c3VwZXJfc2VjcmV0X2tleQ==