apiVersion: v1
kind: Service
metadata:
  name: gestion-trajet-service
  namespace: microservice
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080  
      nodePort: 31000   # Optionnel - seulement si vous voulez un port spécifique
  selector:
    app: gestion-trajet