apiVersion: v1
kind: Service
metadata:
  name: gestion-trajet-service
spec:
  selector:
    app: gestion-trajet
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
