apiVersion: v1
kind: Service
metadata:
  name: gestion-trajet-service
  namespace: microservice-1
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31000 # Optionnel
  selector:
    app: gestion-trajet
