apiVersion: v1
kind: Service
metadata:
  name: gestion-trajet-service
  namespace: microservice-1
spec:
  type: ClusterIP  # Changez en LoadBalancer si besoin d'accès externe
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: gestion-trajet