apiVersion: v1
kind: ConfigMap
metadata:
  name: gestion-trajet-config
  namespace: microservice-1
data:
  NODE_ENV: "production"
  PORT: "8080"
  DB_HOST: "db-host" # Doit matcher le nom du service
  DB_PORT: "5432"
  DB_NAME: "gestion_trajet_db"
  VITE_API_URL: "http://gestion-trajet-service:8080/api"