apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestion-trajet-app
  namespace: microservice-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gestion-trajet
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gestion-trajet
    spec:
      containers:
      - name: app
        image: mbrabaa2023/microservice-1:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: gestion-trajet-config
        - secretRef:
            name: gestion-trajet-secret
        env:  # Ajoutez cette section
        - name: DB_HOST
          value: "db-host"  # Force la valeur
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 45
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true