apiVersion: v1
kind: Secret
metadata:
  name: gestion-trajet-secret
  namespace: microservice-1
type: Opaque
data:
  DB_USER: dHVuaXNidXM=       # "tunisbus" en base64
  DB_PASSWORD: MDAwMA==       # "0000" en base64