apiVersion: v1
kind: Service
metadata:
  name: gestion-trajet-service
  namespace: microservice-1
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: gestion-trajet