apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: microservice-1
spec:
  storageClassName: local-path  # Ajout crucial pour K3s
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi