apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: microservice-1
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/postgres
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain